# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-91332049-1'

menu: 
  - name: About
    link: /about
  - name: People
    submenu:
      - name: Faculty
        link: /people/faculty
      - name: Students
        link: /people/students
  - name: Publications
    link: /publications
  - name: Gallery
    link: /gallery
  - name: Contact
    link: /contact